Add small usage example for retrieving and using a UserInterface object
mezzio/mezzio-authentication pull request #20
Opened 2022-05-27 19:58 UTC by settermjd

|    Q          |   A
|-------------- | ------
| Documentation | yes
| Bugfix        | no
| BC Break      | no
| New Feature   | no
| RFC           | no
| QA            | no

### Description

I don't know if this PR is all that helpful, or stating the obvious, but I glossed over this when I was reading the documentation, so wanted to add it in in case others are doing the same.

2022-05-31 08:22 UTC, Ocramius requested changes

2022-05-31 08:22 UTC, Ocramius commented on docs/book/v1/intro.md
> +```
@settermjd check CI feedback on this, please

2022-06-09 19:34 UTC, froschdesign commented
@settermjd 
> I don't know if this PR is all that helpful…

The entire documentation of the Mezzio's authentication components does not really help. There are no proper instructions on what to do or what to install at all. :disappointed:
Therefore, the addition is okay.

2022-06-09 19:34 UTC, froschdesign commented
@settermjd 
> I don't know if this PR is all that helpful…

The entire documentation of the Mezzio's authentication components does not really help. There are no proper instructions on what to do or what to install at all. :disappointed:
Therefore, the addition is okay.

2022-06-15 13:56 UTC, settermjd commented on docs/book/v1/intro.md
> +```
Shall do.

2022-06-15 14:02 UTC, merged